name: Build and Deploy Angular App from Main Branch

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout main branch
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install project dependencies
      run: npm install
      working-directory: ./

    - name: Install Angular CLI
      run: npm install -g @angular/cli@19

    - name: Build Angular app for production
      run: ng build --configuration production
      working-directory: ./

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}  # This is important to give push permissions
        publish_dir: ./dist/AngularPortfolioWebsite  # Ensure this is correct
